version: "2"

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ddays
      - POSTGRES_USER=lead
      - POSTGRES_PASSWORD=lead

